### ISSUE TITLE
[Suggestion] Deploy to pypi when tag was created

### ISSUE THREAD

**Issue by jairhenrique** [filwaitman/bank-account-validator#13]
@filwaitman on `.travis.yaml` you can add this node to generate an package on pypi when you create a new tag!

```yaml
deploy:
  skip_existing: true
  provider: pypi
  distributions: "sdist bdist_wheel"
  username: "PYPI USER"
  password:
    secure: "PYPI TOKEN"
  on:
    tags: true
    repo: filwaitman/bank-account-validator 
```
